name: Deploy GitHub Pages

on:
  workflow_call:
    inputs:
      formats:
        description: "Output formats (space-separated list)"
        required: false
        default: "html"
        type: string
      version:
        description: "Quarto version"
        required: false
        default: "latest"
        type: string
      tinytex:
        description: "Install TinyTeX"
        required: false
        default: false
        type: boolean
  workflow_dispatch:
    inputs:
      formats:
        description: "Output formats (space-separated list)"
        required: false
        default: "html"
        type: string
      version:
        description: "Quarto version"
        required: false
        default: "release"
        type: string
      tinytex:
        description: "Install TinyTeX"
        required: false
        default: false
        type: boolean
  release:
    types: [published]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4

      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: ${{ github.event.inputs.version }}
          tinytex: ${{ github.event.inputs.tinytex }}

      - name: Render Quarto Project
        shell: bash
        run: |
          echo -e "project:\n  output-dir: _site" > _quarto.yml
          # Render to all formats via for loop to avoid LaTeX error "pdf/beamer" formats
          for format in ${{ github.event.inputs.formats }}; do
            quarto render --to ${format}
          done

      - uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v3
        with:
          path: "_site"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
