name: Release Reveal.js Slides

on:
  workflow_call:
    inputs:
      quarto:
        description: "Quarto version"
        required: true
        default: "release"
        type: string

env:
  GH_TOKEN: ${{ secrets.github_token }} # gh cli
  BRANCH: ci/bump-version
  COMMIT: "ci: bump version for release :rocket:"
  QUARTOVERSION: ${{ inputs.quarto }}

permissions:
  contents: write
  pull-requests: write
  id-token: write
  pages: write

jobs:
  bump-version:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.bump-version.outputs.version }}
      date: ${{ steps.bump-version.outputs.date }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Bump Version
        id: bump-version
        shell: bash
        run: |
          git config --local user.name github-actions[bot]
          git config --local user.email 41898282+github-actions[bot]@users.noreply.github.com
          if git show-ref --quiet refs/heads/${BRANCH}; then
            echo "Branch ${BRANCH} already exists."
            git branch -D "${BRANCH}"
            git push origin --delete "${BRANCH}"
          fi
          git checkout -b "${BRANCH}"

          DATE=$(date +%Y-%m-%d)
          VERSION=${DATE//-/.}
          sed -i "s/^version:.*/version: ${VERSION}/" CITATION.cff
          sed -i "s/^date-released:.*/date-released: \"${DATE}\"/" CITATION.cff
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "date=${DATE}" >> $GITHUB_OUTPUT
          git add CITATION.cff || echo "No changes to add"
          git commit -m "${COMMIT}" || echo "No changes to commit"
          git push --force origin ${BRANCH} || echo "No changes to push"

      - name: Create Pull Request
        shell: bash
        run: |
          sleep 20
          gh pr create --fill-first --base "main" --head "${BRANCH}" --label "Type: CI/CD :robot:"

      - name: Merge Pull Request
        shell: bash
        run: |
          sleep 20
          gh pr merge --auto --squash --delete-branch
          sleep 10
  
  deploy:
    runs-on: ubuntu-latest

    needs: bump-version

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "${{ env.QUARTOVERSION }}"
          tinytex: false

      - name: Render Quarto Project
        shell: bash
        run: |
          npm install -g decktape
          echo -e "project:\n  output-dir: _site\n  post-render:\n    - .github/assets/slides-to-pdf.sh" > _quarto.yml
          quarto render

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_site"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  release:
    runs-on: ubuntu-latest

    needs: deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update branch
        run: |
          git fetch --all
          git checkout main
          git pull origin main

      - name: Release extension on GitHub
        shell: bash
        env:
          DATE: ${{ needs.bump-version.outputs.date }}
          VERSION: ${{ needs.bump-version.outputs.version }}
        run: |
          gh release create ${VERSION} --title "${DATE}" --generate-notes
